/*
 * This file is generated by jOOQ.
*/
package era.uploader.data.database.jooq;


import era.uploader.data.database.jooq.tables.AllAssignments;
import era.uploader.data.database.jooq.tables.Assignment;
import era.uploader.data.database.jooq.tables.Course;
import era.uploader.data.database.jooq.tables.CourseStudent;
import era.uploader.data.database.jooq.tables.QrCodeMapping;
import era.uploader.data.database.jooq.tables.SchemaVersion;
import era.uploader.data.database.jooq.tables.Semester;
import era.uploader.data.database.jooq.tables.SqliteSequence;
import era.uploader.data.database.jooq.tables.Student;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in 
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>all_assignments</code>.
     */
    public static final AllAssignments ALL_ASSIGNMENTS = era.uploader.data.database.jooq.tables.AllAssignments.ALL_ASSIGNMENTS;

    /**
     * The table <code>assignment</code>.
     */
    public static final Assignment ASSIGNMENT = era.uploader.data.database.jooq.tables.Assignment.ASSIGNMENT;

    /**
     * The table <code>course</code>.
     */
    public static final Course COURSE = era.uploader.data.database.jooq.tables.Course.COURSE;

    /**
     * The table <code>course_student</code>.
     */
    public static final CourseStudent COURSE_STUDENT = era.uploader.data.database.jooq.tables.CourseStudent.COURSE_STUDENT;

    /**
     * The table <code>qr_code_mapping</code>.
     */
    public static final QrCodeMapping QR_CODE_MAPPING = era.uploader.data.database.jooq.tables.QrCodeMapping.QR_CODE_MAPPING;

    /**
     * The table <code>schema_version</code>.
     */
    public static final SchemaVersion SCHEMA_VERSION = era.uploader.data.database.jooq.tables.SchemaVersion.SCHEMA_VERSION;

    /**
     * The table <code>Semester</code>.
     */
    public static final Semester SEMESTER = era.uploader.data.database.jooq.tables.Semester.SEMESTER;

    /**
     * The table <code>sqlite_sequence</code>.
     */
    public static final SqliteSequence SQLITE_SEQUENCE = era.uploader.data.database.jooq.tables.SqliteSequence.SQLITE_SEQUENCE;

    /**
     * The table <code>student</code>.
     */
    public static final Student STUDENT = era.uploader.data.database.jooq.tables.Student.STUDENT;
}
