/*
 * This file is generated by jOOQ.
*/
package era.uploader.data.database.jooq;


import era.uploader.data.database.jooq.tables.Assignment;
import era.uploader.data.database.jooq.tables.Course;
import era.uploader.data.database.jooq.tables.CourseStudent;
import era.uploader.data.database.jooq.tables.Page;
import era.uploader.data.database.jooq.tables.SqliteSequence;
import era.uploader.data.database.jooq.tables.Student;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in 
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>assignment</code>.
     */
    public static final Assignment ASSIGNMENT = era.uploader.data.database.jooq.tables.Assignment.ASSIGNMENT;

    /**
     * The table <code>course</code>.
     */
    public static final Course COURSE = era.uploader.data.database.jooq.tables.Course.COURSE;

    /**
     * The table <code>course_student</code>.
     */
    public static final CourseStudent COURSE_STUDENT = era.uploader.data.database.jooq.tables.CourseStudent.COURSE_STUDENT;

    /**
     * The table <code>page</code>.
     */
    public static final Page PAGE = era.uploader.data.database.jooq.tables.Page.PAGE;

    /**
     * The table <code>sqlite_sequence</code>.
     */
    public static final SqliteSequence SQLITE_SEQUENCE = era.uploader.data.database.jooq.tables.SqliteSequence.SQLITE_SEQUENCE;

    /**
     * The table <code>student</code>.
     */
    public static final Student STUDENT = era.uploader.data.database.jooq.tables.Student.STUDENT;
}
