/*
 * This file is generated by jOOQ.
*/
package era.server.data.database.tables.records;


import era.server.data.database.tables.Assignment;

import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record6;
import org.jooq.Row6;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class AssignmentRecord extends UpdatableRecordImpl<AssignmentRecord> implements Record6<String, String, String, Timestamp, String, String> {

    private static final long serialVersionUID = -900427512;

    /**
     * Setter for <code>era.assignment.uuid</code>.
     */
    public AssignmentRecord setUuid(String value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>era.assignment.uuid</code>.
     */
    public String getUuid() {
        return (String) get(0);
    }

    /**
     * Setter for <code>era.assignment.name</code>.
     */
    public AssignmentRecord setName(String value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>era.assignment.name</code>.
     */
    public String getName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>era.assignment.image_file_path</code>.
     */
    public AssignmentRecord setImageFilePath(String value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>era.assignment.image_file_path</code>.
     */
    public String getImageFilePath() {
        return (String) get(2);
    }

    /**
     * Setter for <code>era.assignment.created_date_time</code>.
     */
    public AssignmentRecord setCreatedDateTime(Timestamp value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>era.assignment.created_date_time</code>.
     */
    public Timestamp getCreatedDateTime() {
        return (Timestamp) get(3);
    }

    /**
     * Setter for <code>era.assignment.student_id</code>.
     */
    public AssignmentRecord setStudentId(String value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>era.assignment.student_id</code>.
     */
    public String getStudentId() {
        return (String) get(4);
    }

    /**
     * Setter for <code>era.assignment.course_id</code>.
     */
    public AssignmentRecord setCourseId(String value) {
        set(5, value);
        return this;
    }

    /**
     * Getter for <code>era.assignment.course_id</code>.
     */
    public String getCourseId() {
        return (String) get(5);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<String> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record6 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row6<String, String, String, Timestamp, String, String> fieldsRow() {
        return (Row6) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row6<String, String, String, Timestamp, String, String> valuesRow() {
        return (Row6) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field1() {
        return Assignment.ASSIGNMENT.UUID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return Assignment.ASSIGNMENT.NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return Assignment.ASSIGNMENT.IMAGE_FILE_PATH;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field4() {
        return Assignment.ASSIGNMENT.CREATED_DATE_TIME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field5() {
        return Assignment.ASSIGNMENT.STUDENT_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field6() {
        return Assignment.ASSIGNMENT.COURSE_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component1() {
        return getUuid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component3() {
        return getImageFilePath();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component4() {
        return getCreatedDateTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component5() {
        return getStudentId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component6() {
        return getCourseId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value1() {
        return getUuid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getImageFilePath();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value4() {
        return getCreatedDateTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value5() {
        return getStudentId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value6() {
        return getCourseId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AssignmentRecord value1(String value) {
        setUuid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AssignmentRecord value2(String value) {
        setName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AssignmentRecord value3(String value) {
        setImageFilePath(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AssignmentRecord value4(Timestamp value) {
        setCreatedDateTime(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AssignmentRecord value5(String value) {
        setStudentId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AssignmentRecord value6(String value) {
        setCourseId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AssignmentRecord values(String value1, String value2, String value3, Timestamp value4, String value5, String value6) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached AssignmentRecord
     */
    public AssignmentRecord() {
        super(Assignment.ASSIGNMENT);
    }

    /**
     * Create a detached, initialised AssignmentRecord
     */
    public AssignmentRecord(String uuid, String name, String imageFilePath, Timestamp createdDateTime, String studentId, String courseId) {
        super(Assignment.ASSIGNMENT);

        set(0, uuid);
        set(1, name);
        set(2, imageFilePath);
        set(3, createdDateTime);
        set(4, studentId);
        set(5, courseId);
    }
}
