/*
 * This file is generated by jOOQ.
*/
package era.server.data.database.tables.records;


import era.server.data.database.tables.Assignment;

import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record7;
import org.jooq.Row7;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class AssignmentRecord extends UpdatableRecordImpl<AssignmentRecord> implements Record7<Long, String, String, String, Long, Long, Timestamp> {

    private static final long serialVersionUID = 827218133;

    /**
     * Setter for <code>era.assignment.unique_id</code>.
     */
    public AssignmentRecord setUniqueId(Long value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>era.assignment.unique_id</code>.
     */
    public Long getUniqueId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>era.assignment.uuid</code>.
     */
    public AssignmentRecord setUuid(String value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>era.assignment.uuid</code>.
     */
    public String getUuid() {
        return (String) get(1);
    }

    /**
     * Setter for <code>era.assignment.name</code>.
     */
    public AssignmentRecord setName(String value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>era.assignment.name</code>.
     */
    public String getName() {
        return (String) get(2);
    }

    /**
     * Setter for <code>era.assignment.image_file_path</code>.
     */
    public AssignmentRecord setImageFilePath(String value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>era.assignment.image_file_path</code>.
     */
    public String getImageFilePath() {
        return (String) get(3);
    }

    /**
     * Setter for <code>era.assignment.course_id</code>.
     */
    public AssignmentRecord setCourseId(Long value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>era.assignment.course_id</code>.
     */
    public Long getCourseId() {
        return (Long) get(4);
    }

    /**
     * Setter for <code>era.assignment.student_id</code>.
     */
    public AssignmentRecord setStudentId(Long value) {
        set(5, value);
        return this;
    }

    /**
     * Getter for <code>era.assignment.student_id</code>.
     */
    public Long getStudentId() {
        return (Long) get(5);
    }

    /**
     * Setter for <code>era.assignment.created_date_time</code>.
     */
    public AssignmentRecord setCreatedDateTime(Timestamp value) {
        set(6, value);
        return this;
    }

    /**
     * Getter for <code>era.assignment.created_date_time</code>.
     */
    public Timestamp getCreatedDateTime() {
        return (Timestamp) get(6);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record7 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row7<Long, String, String, String, Long, Long, Timestamp> fieldsRow() {
        return (Row7) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row7<Long, String, String, String, Long, Long, Timestamp> valuesRow() {
        return (Row7) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field1() {
        return Assignment.ASSIGNMENT.UNIQUE_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return Assignment.ASSIGNMENT.UUID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return Assignment.ASSIGNMENT.NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return Assignment.ASSIGNMENT.IMAGE_FILE_PATH;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field5() {
        return Assignment.ASSIGNMENT.COURSE_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field6() {
        return Assignment.ASSIGNMENT.STUDENT_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field7() {
        return Assignment.ASSIGNMENT.CREATED_DATE_TIME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component1() {
        return getUniqueId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getUuid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component3() {
        return getName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component4() {
        return getImageFilePath();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component5() {
        return getCourseId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component6() {
        return getStudentId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component7() {
        return getCreatedDateTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value1() {
        return getUniqueId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getUuid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getImageFilePath();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value5() {
        return getCourseId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value6() {
        return getStudentId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value7() {
        return getCreatedDateTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AssignmentRecord value1(Long value) {
        setUniqueId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AssignmentRecord value2(String value) {
        setUuid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AssignmentRecord value3(String value) {
        setName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AssignmentRecord value4(String value) {
        setImageFilePath(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AssignmentRecord value5(Long value) {
        setCourseId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AssignmentRecord value6(Long value) {
        setStudentId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AssignmentRecord value7(Timestamp value) {
        setCreatedDateTime(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AssignmentRecord values(Long value1, String value2, String value3, String value4, Long value5, Long value6, Timestamp value7) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached AssignmentRecord
     */
    public AssignmentRecord() {
        super(Assignment.ASSIGNMENT);
    }

    /**
     * Create a detached, initialised AssignmentRecord
     */
    public AssignmentRecord(Long uniqueId, String uuid, String name, String imageFilePath, Long courseId, Long studentId, Timestamp createdDateTime) {
        super(Assignment.ASSIGNMENT);

        set(0, uniqueId);
        set(1, uuid);
        set(2, name);
        set(3, imageFilePath);
        set(4, courseId);
        set(5, studentId);
        set(6, createdDateTime);
    }
}
