/*
 * This file is generated by jOOQ.
*/
package era.server.data.database.tables.records;


import era.server.data.database.tables.CourseStudent;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record2;
import org.jooq.Row2;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CourseStudentRecord extends UpdatableRecordImpl<CourseStudentRecord> implements Record2<String, String> {

    private static final long serialVersionUID = -615841558;

    /**
     * Setter for <code>dev.course_student.student_id</code>.
     */
    public CourseStudentRecord setStudentId(String value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>dev.course_student.student_id</code>.
     */
    public String getStudentId() {
        return (String) get(0);
    }

    /**
     * Setter for <code>dev.course_student.course_id</code>.
     */
    public CourseStudentRecord setCourseId(String value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>dev.course_student.course_id</code>.
     */
    public String getCourseId() {
        return (String) get(1);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record2<String, String> key() {
        return (Record2) super.key();
    }

    // -------------------------------------------------------------------------
    // Record2 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row2<String, String> fieldsRow() {
        return (Row2) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row2<String, String> valuesRow() {
        return (Row2) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field1() {
        return CourseStudent.COURSE_STUDENT.STUDENT_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return CourseStudent.COURSE_STUDENT.COURSE_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component1() {
        return getStudentId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getCourseId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value1() {
        return getStudentId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getCourseId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CourseStudentRecord value1(String value) {
        setStudentId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CourseStudentRecord value2(String value) {
        setCourseId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CourseStudentRecord values(String value1, String value2) {
        value1(value1);
        value2(value2);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached CourseStudentRecord
     */
    public CourseStudentRecord() {
        super(CourseStudent.COURSE_STUDENT);
    }

    /**
     * Create a detached, initialised CourseStudentRecord
     */
    public CourseStudentRecord(String studentId, String courseId) {
        super(CourseStudent.COURSE_STUDENT);

        set(0, studentId);
        set(1, courseId);
    }
}
