/*
 * This file is generated by jOOQ.
*/
package era.server.data.database.tables.records;


import era.server.data.database.tables.Semester;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record4;
import org.jooq.Row4;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SemesterRecord extends UpdatableRecordImpl<SemesterRecord> implements Record4<Long, String, String, Integer> {

    private static final long serialVersionUID = -1126722602;

    /**
     * Setter for <code>era.semester.unique_id</code>.
     */
    public SemesterRecord setUniqueId(Long value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>era.semester.unique_id</code>.
     */
    public Long getUniqueId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>era.semester.uuid</code>.
     */
    public SemesterRecord setUuid(String value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>era.semester.uuid</code>.
     */
    public String getUuid() {
        return (String) get(1);
    }

    /**
     * Setter for <code>era.semester.term</code>.
     */
    public SemesterRecord setTerm(String value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>era.semester.term</code>.
     */
    public String getTerm() {
        return (String) get(2);
    }

    /**
     * Setter for <code>era.semester.year</code>.
     */
    public SemesterRecord setYear(Integer value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>era.semester.year</code>.
     */
    public Integer getYear() {
        return (Integer) get(3);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record4 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row4<Long, String, String, Integer> fieldsRow() {
        return (Row4) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row4<Long, String, String, Integer> valuesRow() {
        return (Row4) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field1() {
        return Semester.SEMESTER.UNIQUE_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return Semester.SEMESTER.UUID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return Semester.SEMESTER.TERM;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field4() {
        return Semester.SEMESTER.YEAR;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component1() {
        return getUniqueId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getUuid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component3() {
        return getTerm();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component4() {
        return getYear();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value1() {
        return getUniqueId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getUuid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getTerm();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value4() {
        return getYear();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SemesterRecord value1(Long value) {
        setUniqueId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SemesterRecord value2(String value) {
        setUuid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SemesterRecord value3(String value) {
        setTerm(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SemesterRecord value4(Integer value) {
        setYear(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SemesterRecord values(Long value1, String value2, String value3, Integer value4) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached SemesterRecord
     */
    public SemesterRecord() {
        super(Semester.SEMESTER);
    }

    /**
     * Create a detached, initialised SemesterRecord
     */
    public SemesterRecord(Long uniqueId, String uuid, String term, Integer year) {
        super(Semester.SEMESTER);

        set(0, uniqueId);
        set(1, uuid);
        set(2, term);
        set(3, year);
    }
}
