/*
 * This file is generated by jOOQ.
*/
package era.server.data.database;


import era.server.data.database.tables.Admin;
import era.server.data.database.tables.Assignment;
import era.server.data.database.tables.Course;
import era.server.data.database.tables.CourseStudent;
import era.server.data.database.tables.SchemaVersion;
import era.server.data.database.tables.Semester;
import era.server.data.database.tables.Student;

import javax.annotation.Generated;

import org.jooq.Index;
import org.jooq.OrderField;
import org.jooq.impl.AbstractKeys;


/**
 * A class modelling indexes of tables of the <code>dev</code> schema.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Indexes {

    // -------------------------------------------------------------------------
    // INDEX definitions
    // -------------------------------------------------------------------------

    public static final Index ADMIN_PRIMARY = Indexes0.ADMIN_PRIMARY;
    public static final Index ASSIGNMENT_ASSIGNMENT_COURSE_FK = Indexes0.ASSIGNMENT_ASSIGNMENT_COURSE_FK;
    public static final Index ASSIGNMENT_ASSIGNMENT_STUDENT_IDX = Indexes0.ASSIGNMENT_ASSIGNMENT_STUDENT_IDX;
    public static final Index ASSIGNMENT_PRIMARY = Indexes0.ASSIGNMENT_PRIMARY;
    public static final Index COURSE_COURSE_SEMESTER_FK = Indexes0.COURSE_COURSE_SEMESTER_FK;
    public static final Index COURSE_COURSE_SEMESTER_NAME_UK = Indexes0.COURSE_COURSE_SEMESTER_NAME_UK;
    public static final Index COURSE_PRIMARY = Indexes0.COURSE_PRIMARY;
    public static final Index COURSE_STUDENT_COURSE_STUDENT_STUDENT_FK = Indexes0.COURSE_STUDENT_COURSE_STUDENT_STUDENT_FK;
    public static final Index COURSE_STUDENT_PRIMARY = Indexes0.COURSE_STUDENT_PRIMARY;
    public static final Index SCHEMA_VERSION_PRIMARY = Indexes0.SCHEMA_VERSION_PRIMARY;
    public static final Index SCHEMA_VERSION_SCHEMA_VERSION_S_IDX = Indexes0.SCHEMA_VERSION_SCHEMA_VERSION_S_IDX;
    public static final Index SEMESTER_PRIMARY = Indexes0.SEMESTER_PRIMARY;
    public static final Index SEMESTER_SEMESTER_TERM_YEAR = Indexes0.SEMESTER_SEMESTER_TERM_YEAR;
    public static final Index STUDENT_PRIMARY = Indexes0.STUDENT_PRIMARY;
    public static final Index STUDENT_STUDENT_USERNAME_UK = Indexes0.STUDENT_STUDENT_USERNAME_UK;

    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Indexes0 extends AbstractKeys {
        public static Index ADMIN_PRIMARY = createIndex("PRIMARY", Admin.ADMIN, new OrderField[] { Admin.ADMIN.STUDENT_ID }, true);
        public static Index ASSIGNMENT_ASSIGNMENT_COURSE_FK = createIndex("assignment_course_fk", Assignment.ASSIGNMENT, new OrderField[] { Assignment.ASSIGNMENT.COURSE_ID }, false);
        public static Index ASSIGNMENT_ASSIGNMENT_STUDENT_IDX = createIndex("assignment_student_idx", Assignment.ASSIGNMENT, new OrderField[] { Assignment.ASSIGNMENT.STUDENT_ID }, false);
        public static Index ASSIGNMENT_PRIMARY = createIndex("PRIMARY", Assignment.ASSIGNMENT, new OrderField[] { Assignment.ASSIGNMENT.UUID }, true);
        public static Index COURSE_COURSE_SEMESTER_FK = createIndex("course_semester_fk", Course.COURSE, new OrderField[] { Course.COURSE.SEMESTER_ID }, false);
        public static Index COURSE_COURSE_SEMESTER_NAME_UK = createIndex("course_semester_name_uk", Course.COURSE, new OrderField[] { Course.COURSE.NAME, Course.COURSE.SEMESTER_ID }, true);
        public static Index COURSE_PRIMARY = createIndex("PRIMARY", Course.COURSE, new OrderField[] { Course.COURSE.UUID }, true);
        public static Index COURSE_STUDENT_COURSE_STUDENT_STUDENT_FK = createIndex("course_student_student_fk", CourseStudent.COURSE_STUDENT, new OrderField[] { CourseStudent.COURSE_STUDENT.STUDENT_ID }, false);
        public static Index COURSE_STUDENT_PRIMARY = createIndex("PRIMARY", CourseStudent.COURSE_STUDENT, new OrderField[] { CourseStudent.COURSE_STUDENT.COURSE_ID, CourseStudent.COURSE_STUDENT.STUDENT_ID }, true);
        public static Index SCHEMA_VERSION_PRIMARY = createIndex("PRIMARY", SchemaVersion.SCHEMA_VERSION, new OrderField[] { SchemaVersion.SCHEMA_VERSION.INSTALLED_RANK }, true);
        public static Index SCHEMA_VERSION_SCHEMA_VERSION_S_IDX = createIndex("schema_version_s_idx", SchemaVersion.SCHEMA_VERSION, new OrderField[] { SchemaVersion.SCHEMA_VERSION.SUCCESS }, false);
        public static Index SEMESTER_PRIMARY = createIndex("PRIMARY", Semester.SEMESTER, new OrderField[] { Semester.SEMESTER.UUID }, true);
        public static Index SEMESTER_SEMESTER_TERM_YEAR = createIndex("semester_term_year", Semester.SEMESTER, new OrderField[] { Semester.SEMESTER.TERM, Semester.SEMESTER.YEAR }, true);
        public static Index STUDENT_PRIMARY = createIndex("PRIMARY", Student.STUDENT, new OrderField[] { Student.STUDENT.UUID }, true);
        public static Index STUDENT_STUDENT_USERNAME_UK = createIndex("student_username_uk", Student.STUDENT, new OrderField[] { Student.STUDENT.USERNAME }, true);
    }
}
