/*
 * This file is generated by jOOQ.
*/
package era.server.data.database;


import era.server.data.database.tables.Admin;
import era.server.data.database.tables.Assignment;
import era.server.data.database.tables.Course;
import era.server.data.database.tables.CourseStudent;
import era.server.data.database.tables.SchemaVersion;
import era.server.data.database.tables.Semester;
import era.server.data.database.tables.Student;
import era.server.data.database.tables.records.AdminRecord;
import era.server.data.database.tables.records.AssignmentRecord;
import era.server.data.database.tables.records.CourseRecord;
import era.server.data.database.tables.records.CourseStudentRecord;
import era.server.data.database.tables.records.SchemaVersionRecord;
import era.server.data.database.tables.records.SemesterRecord;
import era.server.data.database.tables.records.StudentRecord;

import javax.annotation.Generated;

import org.jooq.ForeignKey;
import org.jooq.UniqueKey;
import org.jooq.impl.AbstractKeys;


/**
 * A class modelling foreign key relationships and constraints of tables of 
 * the <code>dev</code> schema.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // IDENTITY definitions
    // -------------------------------------------------------------------------


    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<AdminRecord> KEY_ADMIN_PRIMARY = UniqueKeys0.KEY_ADMIN_PRIMARY;
    public static final UniqueKey<AssignmentRecord> KEY_ASSIGNMENT_PRIMARY = UniqueKeys0.KEY_ASSIGNMENT_PRIMARY;
    public static final UniqueKey<CourseRecord> KEY_COURSE_PRIMARY = UniqueKeys0.KEY_COURSE_PRIMARY;
    public static final UniqueKey<CourseRecord> KEY_COURSE_COURSE_SEMESTER_NAME_UK = UniqueKeys0.KEY_COURSE_COURSE_SEMESTER_NAME_UK;
    public static final UniqueKey<CourseStudentRecord> KEY_COURSE_STUDENT_PRIMARY = UniqueKeys0.KEY_COURSE_STUDENT_PRIMARY;
    public static final UniqueKey<SchemaVersionRecord> KEY_SCHEMA_VERSION_PRIMARY = UniqueKeys0.KEY_SCHEMA_VERSION_PRIMARY;
    public static final UniqueKey<SemesterRecord> KEY_SEMESTER_PRIMARY = UniqueKeys0.KEY_SEMESTER_PRIMARY;
    public static final UniqueKey<SemesterRecord> KEY_SEMESTER_SEMESTER_TERM_YEAR = UniqueKeys0.KEY_SEMESTER_SEMESTER_TERM_YEAR;
    public static final UniqueKey<StudentRecord> KEY_STUDENT_PRIMARY = UniqueKeys0.KEY_STUDENT_PRIMARY;
    public static final UniqueKey<StudentRecord> KEY_STUDENT_STUDENT_USERNAME_UK = UniqueKeys0.KEY_STUDENT_STUDENT_USERNAME_UK;

    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------

    public static final ForeignKey<AdminRecord, StudentRecord> ADMIN_STUDENT_FK = ForeignKeys0.ADMIN_STUDENT_FK;
    public static final ForeignKey<AssignmentRecord, StudentRecord> ASSIGNMENT_STUDENT_FK = ForeignKeys0.ASSIGNMENT_STUDENT_FK;
    public static final ForeignKey<AssignmentRecord, CourseRecord> ASSIGNMENT_COURSE_FK = ForeignKeys0.ASSIGNMENT_COURSE_FK;
    public static final ForeignKey<CourseRecord, SemesterRecord> COURSE_SEMESTER_FK = ForeignKeys0.COURSE_SEMESTER_FK;
    public static final ForeignKey<CourseStudentRecord, StudentRecord> COURSE_STUDENT_STUDENT_FK = ForeignKeys0.COURSE_STUDENT_STUDENT_FK;
    public static final ForeignKey<CourseStudentRecord, CourseRecord> COURSE_STUDENT_COURSE_FK = ForeignKeys0.COURSE_STUDENT_COURSE_FK;

    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class UniqueKeys0 extends AbstractKeys {
        public static final UniqueKey<AdminRecord> KEY_ADMIN_PRIMARY = createUniqueKey(Admin.ADMIN, "KEY_admin_PRIMARY", Admin.ADMIN.STUDENT_ID);
        public static final UniqueKey<AssignmentRecord> KEY_ASSIGNMENT_PRIMARY = createUniqueKey(Assignment.ASSIGNMENT, "KEY_assignment_PRIMARY", Assignment.ASSIGNMENT.UUID);
        public static final UniqueKey<CourseRecord> KEY_COURSE_PRIMARY = createUniqueKey(Course.COURSE, "KEY_course_PRIMARY", Course.COURSE.UUID);
        public static final UniqueKey<CourseRecord> KEY_COURSE_COURSE_SEMESTER_NAME_UK = createUniqueKey(Course.COURSE, "KEY_course_course_semester_name_uk", Course.COURSE.NAME, Course.COURSE.SEMESTER_ID);
        public static final UniqueKey<CourseStudentRecord> KEY_COURSE_STUDENT_PRIMARY = createUniqueKey(CourseStudent.COURSE_STUDENT, "KEY_course_student_PRIMARY", CourseStudent.COURSE_STUDENT.COURSE_ID, CourseStudent.COURSE_STUDENT.STUDENT_ID);
        public static final UniqueKey<SchemaVersionRecord> KEY_SCHEMA_VERSION_PRIMARY = createUniqueKey(SchemaVersion.SCHEMA_VERSION, "KEY_schema_version_PRIMARY", SchemaVersion.SCHEMA_VERSION.INSTALLED_RANK);
        public static final UniqueKey<SemesterRecord> KEY_SEMESTER_PRIMARY = createUniqueKey(Semester.SEMESTER, "KEY_semester_PRIMARY", Semester.SEMESTER.UUID);
        public static final UniqueKey<SemesterRecord> KEY_SEMESTER_SEMESTER_TERM_YEAR = createUniqueKey(Semester.SEMESTER, "KEY_semester_semester_term_year", Semester.SEMESTER.TERM, Semester.SEMESTER.YEAR);
        public static final UniqueKey<StudentRecord> KEY_STUDENT_PRIMARY = createUniqueKey(Student.STUDENT, "KEY_student_PRIMARY", Student.STUDENT.UUID);
        public static final UniqueKey<StudentRecord> KEY_STUDENT_STUDENT_USERNAME_UK = createUniqueKey(Student.STUDENT, "KEY_student_student_username_uk", Student.STUDENT.USERNAME);
    }

    private static class ForeignKeys0 extends AbstractKeys {
        public static final ForeignKey<AdminRecord, StudentRecord> ADMIN_STUDENT_FK = createForeignKey(era.server.data.database.Keys.KEY_STUDENT_PRIMARY, Admin.ADMIN, "admin_student_fk", Admin.ADMIN.STUDENT_ID);
        public static final ForeignKey<AssignmentRecord, StudentRecord> ASSIGNMENT_STUDENT_FK = createForeignKey(era.server.data.database.Keys.KEY_STUDENT_PRIMARY, Assignment.ASSIGNMENT, "assignment_student_fk", Assignment.ASSIGNMENT.STUDENT_ID);
        public static final ForeignKey<AssignmentRecord, CourseRecord> ASSIGNMENT_COURSE_FK = createForeignKey(era.server.data.database.Keys.KEY_COURSE_PRIMARY, Assignment.ASSIGNMENT, "assignment_course_fk", Assignment.ASSIGNMENT.COURSE_ID);
        public static final ForeignKey<CourseRecord, SemesterRecord> COURSE_SEMESTER_FK = createForeignKey(era.server.data.database.Keys.KEY_SEMESTER_PRIMARY, Course.COURSE, "course_semester_fk", Course.COURSE.SEMESTER_ID);
        public static final ForeignKey<CourseStudentRecord, StudentRecord> COURSE_STUDENT_STUDENT_FK = createForeignKey(era.server.data.database.Keys.KEY_STUDENT_PRIMARY, CourseStudent.COURSE_STUDENT, "course_student_student_fk", CourseStudent.COURSE_STUDENT.STUDENT_ID);
        public static final ForeignKey<CourseStudentRecord, CourseRecord> COURSE_STUDENT_COURSE_FK = createForeignKey(era.server.data.database.Keys.KEY_COURSE_PRIMARY, CourseStudent.COURSE_STUDENT, "course_student_course_fk", CourseStudent.COURSE_STUDENT.COURSE_ID);
    }
}
