ALTER TABLE student
  MODIFY COLUMN uuid VARCHAR(36) NOT NULL;
ALTER TABLE course
  MODIFY COLUMN uuid VARCHAR(36) NOT NULL;
ALTER TABLE assignment
  MODIFY COLUMN uuid VARCHAR(36) NOT NULL;
ALTER TABLE semester
  MODIFY COLUMN uuid VARCHAR(36) NOT NULL;


