ALTER TABLE student
  MODIFY COLUMN uuid VARCHAR(36) NOT NULL DEFAULT UUID();
ALTER TABLE course
  MODIFY COLUMN uuid VARCHAR(36) NOT NULL DEFAULT UUID();
ALTER TABLE assignment
  MODIFY COLUMN uuid VARCHAR(36) NOT NULL DEFAULT UUID();
ALTER TABLE semester
  MODIFY COLUMN uuid VARCHAR(36) NOT NULL DEFAULT UUID();


