/*
 * This file is generated by jOOQ.
*/
package era.uploader.data.database.jooq.tables.records;


import era.uploader.data.database.jooq.tables.Page;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record4;
import org.jooq.Row4;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PageRecord extends UpdatableRecordImpl<PageRecord> implements Record4<String, Integer, Integer, Integer> {

    private static final long serialVersionUID = 762479183;

    /**
     * Setter for <code>page.uuid</code>.
     */
    public PageRecord setUuid(String value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>page.uuid</code>.
     */
    public String getUuid() {
        return (String) get(0);
    }

    /**
     * Setter for <code>page.sequence_number</code>.
     */
    public PageRecord setSequenceNumber(Integer value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>page.sequence_number</code>.
     */
    public Integer getSequenceNumber() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>page.assignment_id</code>.
     */
    public PageRecord setAssignmentId(Integer value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>page.assignment_id</code>.
     */
    public Integer getAssignmentId() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>page.student_id</code>.
     */
    public PageRecord setStudentId(Integer value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>page.student_id</code>.
     */
    public Integer getStudentId() {
        return (Integer) get(3);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<String> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record4 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row4<String, Integer, Integer, Integer> fieldsRow() {
        return (Row4) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row4<String, Integer, Integer, Integer> valuesRow() {
        return (Row4) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field1() {
        return Page.PAGE.UUID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field2() {
        return Page.PAGE.SEQUENCE_NUMBER;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field3() {
        return Page.PAGE.ASSIGNMENT_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field4() {
        return Page.PAGE.STUDENT_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component1() {
        return getUuid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component2() {
        return getSequenceNumber();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component3() {
        return getAssignmentId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component4() {
        return getStudentId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value1() {
        return getUuid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value2() {
        return getSequenceNumber();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value3() {
        return getAssignmentId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value4() {
        return getStudentId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PageRecord value1(String value) {
        setUuid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PageRecord value2(Integer value) {
        setSequenceNumber(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PageRecord value3(Integer value) {
        setAssignmentId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PageRecord value4(Integer value) {
        setStudentId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PageRecord values(String value1, Integer value2, Integer value3, Integer value4) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached PageRecord
     */
    public PageRecord() {
        super(Page.PAGE);
    }

    /**
     * Create a detached, initialised PageRecord
     */
    public PageRecord(String uuid, Integer sequenceNumber, Integer assignmentId, Integer studentId) {
        super(Page.PAGE);

        set(0, uuid);
        set(1, sequenceNumber);
        set(2, assignmentId);
        set(3, studentId);
    }
}
