/*
 * This file is generated by jOOQ.
*/
package era.uploader.data.database.jooq.tables;


import era.uploader.data.database.jooq.DefaultSchema;
import era.uploader.data.database.jooq.Indexes;
import era.uploader.data.database.jooq.Keys;
import era.uploader.data.database.jooq.tables.records.PageRecord;

import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Page extends TableImpl<PageRecord> {

    private static final long serialVersionUID = 790276481;

    /**
     * The reference instance of <code>page</code>
     */
    public static final Page PAGE = new Page();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<PageRecord> getRecordType() {
        return PageRecord.class;
    }

    /**
     * The column <code>page.uuid</code>.
     */
    public final TableField<PageRecord, String> UUID = createField("uuid", org.jooq.impl.SQLDataType.CLOB.nullable(false), this, "");

    /**
     * The column <code>page.sequence_number</code>.
     */
    public final TableField<PageRecord, Integer> SEQUENCE_NUMBER = createField("sequence_number", org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * The column <code>page.assignment_id</code>.
     */
    public final TableField<PageRecord, Integer> ASSIGNMENT_ID = createField("assignment_id", org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * The column <code>page.student_id</code>.
     */
    public final TableField<PageRecord, Integer> STUDENT_ID = createField("student_id", org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * Create a <code>page</code> table reference
     */
    public Page() {
        this(DSL.name("page"), null);
    }

    /**
     * Create an aliased <code>page</code> table reference
     */
    public Page(String alias) {
        this(DSL.name(alias), PAGE);
    }

    /**
     * Create an aliased <code>page</code> table reference
     */
    public Page(Name alias) {
        this(alias, PAGE);
    }

    private Page(Name alias, Table<PageRecord> aliased) {
        this(alias, aliased, null);
    }

    private Page(Name alias, Table<PageRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return DefaultSchema.DEFAULT_SCHEMA;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.SQLITE_AUTOINDEX_PAGE_1);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<PageRecord> getPrimaryKey() {
        return Keys.PK_PAGE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<PageRecord>> getKeys() {
        return Arrays.<UniqueKey<PageRecord>>asList(Keys.PK_PAGE);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<ForeignKey<PageRecord, ?>> getReferences() {
        return Arrays.<ForeignKey<PageRecord, ?>>asList(Keys.FK_PAGE_ASSIGNMENT_1, Keys.FK_PAGE_STUDENT_1);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Page as(String alias) {
        return new Page(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Page as(Name alias) {
        return new Page(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public Page rename(String name) {
        return new Page(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Page rename(Name name) {
        return new Page(name, null);
    }
}
