/*
 * This file is generated by jOOQ.
*/
package era.uploader.data.database.jooq.tables;


import era.uploader.data.database.jooq.DefaultSchema;
import era.uploader.data.database.jooq.Keys;
import era.uploader.data.database.jooq.tables.records.SemesterRecord;

import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Identity;
import org.jooq.Name;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Semester extends TableImpl<SemesterRecord> {

    private static final long serialVersionUID = -1222197421;

    /**
     * The reference instance of <code>semester</code>
     */
    public static final Semester SEMESTER = new Semester();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<SemesterRecord> getRecordType() {
        return SemesterRecord.class;
    }

    /**
     * The column <code>semester.unique_id</code>.
     */
    public final TableField<SemesterRecord, Integer> UNIQUE_ID = createField("unique_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false).identity(true), this, "");

    /**
     * The column <code>semester.term</code>.
     */
    public final TableField<SemesterRecord, String> TERM = createField("term", org.jooq.impl.SQLDataType.CLOB.nullable(false), this, "");

    /**
     * The column <code>semester.year</code>.
     */
    public final TableField<SemesterRecord, Integer> YEAR = createField("year", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * Create a <code>semester</code> table reference
     */
    public Semester() {
        this(DSL.name("semester"), null);
    }

    /**
     * Create an aliased <code>semester</code> table reference
     */
    public Semester(String alias) {
        this(DSL.name(alias), SEMESTER);
    }

    /**
     * Create an aliased <code>semester</code> table reference
     */
    public Semester(Name alias) {
        this(alias, SEMESTER);
    }

    private Semester(Name alias, Table<SemesterRecord> aliased) {
        this(alias, aliased, null);
    }

    private Semester(Name alias, Table<SemesterRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return DefaultSchema.DEFAULT_SCHEMA;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<SemesterRecord, Integer> getIdentity() {
        return Keys.IDENTITY_SEMESTER;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<SemesterRecord> getPrimaryKey() {
        return Keys.PK_SEMESTER;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<SemesterRecord>> getKeys() {
        return Arrays.<UniqueKey<SemesterRecord>>asList(Keys.PK_SEMESTER);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Semester as(String alias) {
        return new Semester(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Semester as(Name alias) {
        return new Semester(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public Semester rename(String name) {
        return new Semester(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Semester rename(Name name) {
        return new Semester(name, null);
    }
}
