/*
 * This file is generated by jOOQ.
*/
package era.server.database;


import era.server.database.tables.Assignment;
import era.server.database.tables.Course;
import era.server.database.tables.CourseStudent;
import era.server.database.tables.Student;

import javax.annotation.Generated;

import org.jooq.Index;
import org.jooq.OrderField;
import org.jooq.impl.AbstractKeys;


/**
 * A class modelling indexes of tables of the <code>era</code> schema.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Indexes {

    // -------------------------------------------------------------------------
    // INDEX definitions
    // -------------------------------------------------------------------------

    public static final Index ASSIGNMENT_ASSIGNMENT_COURSE_FK = Indexes0.ASSIGNMENT_ASSIGNMENT_COURSE_FK;
    public static final Index ASSIGNMENT_ASSIGNMENT_STUDENT_FK = Indexes0.ASSIGNMENT_ASSIGNMENT_STUDENT_FK;
    public static final Index ASSIGNMENT_PRIMARY = Indexes0.ASSIGNMENT_PRIMARY;
    public static final Index COURSE_PRIMARY = Indexes0.COURSE_PRIMARY;
    public static final Index COURSE_STUDENT_COURSE_STUDENT_STUDENT_FK = Indexes0.COURSE_STUDENT_COURSE_STUDENT_STUDENT_FK;
    public static final Index COURSE_STUDENT_PRIMARY = Indexes0.COURSE_STUDENT_PRIMARY;
    public static final Index STUDENT_PRIMARY = Indexes0.STUDENT_PRIMARY;
    public static final Index STUDENT_STUDENT_EMAIL_UK = Indexes0.STUDENT_STUDENT_EMAIL_UK;
    public static final Index STUDENT_STUDENT_USERNAME_UK = Indexes0.STUDENT_STUDENT_USERNAME_UK;

    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Indexes0 extends AbstractKeys {
        public static Index ASSIGNMENT_ASSIGNMENT_COURSE_FK = createIndex("assignment_course_fk", Assignment.ASSIGNMENT, new OrderField[] { Assignment.ASSIGNMENT.COURSE_ID }, false);
        public static Index ASSIGNMENT_ASSIGNMENT_STUDENT_FK = createIndex("assignment_student_fk", Assignment.ASSIGNMENT, new OrderField[] { Assignment.ASSIGNMENT.STUDENT_ID }, false);
        public static Index ASSIGNMENT_PRIMARY = createIndex("PRIMARY", Assignment.ASSIGNMENT, new OrderField[] { Assignment.ASSIGNMENT.UNIQUE_ID }, true);
        public static Index COURSE_PRIMARY = createIndex("PRIMARY", Course.COURSE, new OrderField[] { Course.COURSE.UNIQUE_ID }, true);
        public static Index COURSE_STUDENT_COURSE_STUDENT_STUDENT_FK = createIndex("course_student_student_fk", CourseStudent.COURSE_STUDENT, new OrderField[] { CourseStudent.COURSE_STUDENT.STUDENT_ID }, false);
        public static Index COURSE_STUDENT_PRIMARY = createIndex("PRIMARY", CourseStudent.COURSE_STUDENT, new OrderField[] { CourseStudent.COURSE_STUDENT.COURSE_ID, CourseStudent.COURSE_STUDENT.STUDENT_ID }, true);
        public static Index STUDENT_PRIMARY = createIndex("PRIMARY", Student.STUDENT, new OrderField[] { Student.STUDENT.UNIQUE_ID }, true);
        public static Index STUDENT_STUDENT_EMAIL_UK = createIndex("student_email_uk", Student.STUDENT, new OrderField[] { Student.STUDENT.EMAIL }, true);
        public static Index STUDENT_STUDENT_USERNAME_UK = createIndex("student_username_uk", Student.STUDENT, new OrderField[] { Student.STUDENT.USERNAME }, true);
    }
}
