/*
 * This file is generated by jOOQ.
*/
package era.server.database;


import era.server.database.tables.Assignment;
import era.server.database.tables.Course;
import era.server.database.tables.CourseStudent;
import era.server.database.tables.Student;
import era.server.database.tables.records.AssignmentRecord;
import era.server.database.tables.records.CourseRecord;
import era.server.database.tables.records.CourseStudentRecord;
import era.server.database.tables.records.StudentRecord;

import javax.annotation.Generated;

import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.UniqueKey;
import org.jooq.impl.AbstractKeys;


/**
 * A class modelling foreign key relationships and constraints of tables of 
 * the <code>era</code> schema.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // IDENTITY definitions
    // -------------------------------------------------------------------------

    public static final Identity<AssignmentRecord, Long> IDENTITY_ASSIGNMENT = Identities0.IDENTITY_ASSIGNMENT;
    public static final Identity<CourseRecord, Long> IDENTITY_COURSE = Identities0.IDENTITY_COURSE;
    public static final Identity<StudentRecord, Long> IDENTITY_STUDENT = Identities0.IDENTITY_STUDENT;

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<AssignmentRecord> KEY_ASSIGNMENT_PRIMARY = UniqueKeys0.KEY_ASSIGNMENT_PRIMARY;
    public static final UniqueKey<CourseRecord> KEY_COURSE_PRIMARY = UniqueKeys0.KEY_COURSE_PRIMARY;
    public static final UniqueKey<CourseStudentRecord> KEY_COURSE_STUDENT_PRIMARY = UniqueKeys0.KEY_COURSE_STUDENT_PRIMARY;
    public static final UniqueKey<StudentRecord> KEY_STUDENT_PRIMARY = UniqueKeys0.KEY_STUDENT_PRIMARY;
    public static final UniqueKey<StudentRecord> KEY_STUDENT_STUDENT_USERNAME_UK = UniqueKeys0.KEY_STUDENT_STUDENT_USERNAME_UK;
    public static final UniqueKey<StudentRecord> KEY_STUDENT_STUDENT_EMAIL_UK = UniqueKeys0.KEY_STUDENT_STUDENT_EMAIL_UK;

    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------

    public static final ForeignKey<AssignmentRecord, CourseRecord> ASSIGNMENT_COURSE_FK = ForeignKeys0.ASSIGNMENT_COURSE_FK;
    public static final ForeignKey<AssignmentRecord, StudentRecord> ASSIGNMENT_STUDENT_FK = ForeignKeys0.ASSIGNMENT_STUDENT_FK;
    public static final ForeignKey<CourseStudentRecord, CourseRecord> COURSE_STUDENT_COURSE_FK = ForeignKeys0.COURSE_STUDENT_COURSE_FK;
    public static final ForeignKey<CourseStudentRecord, StudentRecord> COURSE_STUDENT_STUDENT_FK = ForeignKeys0.COURSE_STUDENT_STUDENT_FK;

    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Identities0 extends AbstractKeys {
        public static Identity<AssignmentRecord, Long> IDENTITY_ASSIGNMENT = createIdentity(Assignment.ASSIGNMENT, Assignment.ASSIGNMENT.UNIQUE_ID);
        public static Identity<CourseRecord, Long> IDENTITY_COURSE = createIdentity(Course.COURSE, Course.COURSE.UNIQUE_ID);
        public static Identity<StudentRecord, Long> IDENTITY_STUDENT = createIdentity(Student.STUDENT, Student.STUDENT.UNIQUE_ID);
    }

    private static class UniqueKeys0 extends AbstractKeys {
        public static final UniqueKey<AssignmentRecord> KEY_ASSIGNMENT_PRIMARY = createUniqueKey(Assignment.ASSIGNMENT, "KEY_assignment_PRIMARY", Assignment.ASSIGNMENT.UNIQUE_ID);
        public static final UniqueKey<CourseRecord> KEY_COURSE_PRIMARY = createUniqueKey(Course.COURSE, "KEY_course_PRIMARY", Course.COURSE.UNIQUE_ID);
        public static final UniqueKey<CourseStudentRecord> KEY_COURSE_STUDENT_PRIMARY = createUniqueKey(CourseStudent.COURSE_STUDENT, "KEY_course_student_PRIMARY", CourseStudent.COURSE_STUDENT.COURSE_ID, CourseStudent.COURSE_STUDENT.STUDENT_ID);
        public static final UniqueKey<StudentRecord> KEY_STUDENT_PRIMARY = createUniqueKey(Student.STUDENT, "KEY_student_PRIMARY", Student.STUDENT.UNIQUE_ID);
        public static final UniqueKey<StudentRecord> KEY_STUDENT_STUDENT_USERNAME_UK = createUniqueKey(Student.STUDENT, "KEY_student_student_username_uk", Student.STUDENT.USERNAME);
        public static final UniqueKey<StudentRecord> KEY_STUDENT_STUDENT_EMAIL_UK = createUniqueKey(Student.STUDENT, "KEY_student_student_email_uk", Student.STUDENT.EMAIL);
    }

    private static class ForeignKeys0 extends AbstractKeys {
        public static final ForeignKey<AssignmentRecord, CourseRecord> ASSIGNMENT_COURSE_FK = createForeignKey(era.server.database.Keys.KEY_COURSE_PRIMARY, Assignment.ASSIGNMENT, "assignment_course_fk", Assignment.ASSIGNMENT.COURSE_ID);
        public static final ForeignKey<AssignmentRecord, StudentRecord> ASSIGNMENT_STUDENT_FK = createForeignKey(era.server.database.Keys.KEY_STUDENT_PRIMARY, Assignment.ASSIGNMENT, "assignment_student_fk", Assignment.ASSIGNMENT.STUDENT_ID);
        public static final ForeignKey<CourseStudentRecord, CourseRecord> COURSE_STUDENT_COURSE_FK = createForeignKey(era.server.database.Keys.KEY_COURSE_PRIMARY, CourseStudent.COURSE_STUDENT, "course_student_course_fk", CourseStudent.COURSE_STUDENT.COURSE_ID);
        public static final ForeignKey<CourseStudentRecord, StudentRecord> COURSE_STUDENT_STUDENT_FK = createForeignKey(era.server.database.Keys.KEY_STUDENT_PRIMARY, CourseStudent.COURSE_STUDENT, "course_student_student_fk", CourseStudent.COURSE_STUDENT.STUDENT_ID);
    }
}
