/*
 * This file is generated by jOOQ.
*/
package era.server.database;


import era.server.database.tables.Assignment;
import era.server.database.tables.Course;
import era.server.database.tables.CourseStudent;
import era.server.database.tables.Student;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in era
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>era.assignment</code>.
     */
    public static final Assignment ASSIGNMENT = era.server.database.tables.Assignment.ASSIGNMENT;

    /**
     * The table <code>era.course</code>.
     */
    public static final Course COURSE = era.server.database.tables.Course.COURSE;

    /**
     * The table <code>era.course_student</code>.
     */
    public static final CourseStudent COURSE_STUDENT = era.server.database.tables.CourseStudent.COURSE_STUDENT;

    /**
     * The table <code>era.student</code>.
     */
    public static final Student STUDENT = era.server.database.tables.Student.STUDENT;
}
